# Generated by Django 3.0.8 on 2020-09-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.CharField(max_length=300)),
                ('poster_path', models.CharField(max_length=100)),
                ('original_title', models.CharField(max_length=100)),
                ('original_language', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=60)),
                ('release_date', models.DateField()),
                ('rating', models.DecimalField(decimal_places=1, default=5, max_digits=2)),
                ('genre_id', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
    ]
